name: Update Deps
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0/6 * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PUSH_TO_REPO_TOKEN }}
      - uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'zulu'
      - uses: markelliot/update-gradle-deps@v1
        with:
          push-to-repo-token: ${{ secrets.GH_PUSH_TO_REPO_TOKEN }}
          commit-user: jayad-bot
          commit-email: jayad-bot@users.noreply.github.com
          primary-branch: main
