name: Check PR
on: [pull_request]

jobs:
  build:
    name: Check PR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'zulu'
      - name: Build
        run: ./gradlew --no-daemon build
